@server=http://localhost:4004
@username=alice
@password=


### GET1
GET {{server}}/mcps
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

### createAribaPurchaseRequisition


POST {{server}}/mcps/createAribaPurchaseRequisition
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "requesterId": "requesterId-6325225",
  "productName": "productName-6325225",
  "description": "description-6325225",
  "quantity": 19,
  "price": 803071617.29,
  "currency": "currency-6325225",
  "supplierId": "supplierId-6325225",
  "needByDate": "needByDate-6325225",
  "companyCode": "companyCode-6325225",
  "glAccount": "glAccount-6325225",
  "costCenter": "costCenter-6325225",
  "isSourcingPr": false,
  "type": "contract"
}


### createAribaPurchaseRequisition
POST {{server}}/mcps/createAribaPurchaseRequisition
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "requesterId": "A.sadashiv@lipton.com",
  "companyCode": "1000",
  "supplierId": "SU_INTERNAL86052967",
  "quantity": 19,
  "price": 803071617.29,
  "currency": "AUD",
  "needByDate": "2026-03-10",
  "glAccount": "00124000000",
  
  "productName": "productName-6325225",
  "description": "description-6325225",
  "costCenter": "costCenter-6325225",
  "isSourcingPr": false,
  "type": "quotation"
}
